spring.application.name=mcpserverstdio
server.port=8082

##############################################
# POSTGRESQL DATABASE
##############################################
spring.datasource.url=jdbc:postgresql://localhost:5432/chatmemory
spring.datasource.username=postgres
spring.datasource.password=Hanu@2025
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

#Since we are using this for mcp server stdio we will not be using any web application type so we will set it to none
spring.main.web-application-type=none
spring.ai.mcp.server.stdio=true
logging.level.root=ERROR
spring.main.banner-mode=off
