spring.application.name=SpringAIDemo
server.port=8085

# OpenAI API Key
spring.ai.openai.api-key=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
spring.ai.anthropic.api-key=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
spring.ai.ollama.chat.options.model=deepseek-r1:7b
spring.ai.ollama.completion.options.model=deepseek-r1:7b

