spring.application.name=openai

#Docker container running Gemma3 on localhost:12434
spring.ai.openai.base-url=http://localhost:12434/v1
spring.ai.openai.api-key=dummy
spring.ai.openai.chat.model=ai/gemma3


logging.level.com.openai=TRACE
logging.level.org.springframework.ai=TRACE
logging.level.okhttp3=DEBUG
logging.level.okhttp3.logging.HttpLoggingInterceptor=TRACE