spring.application.name=mcpclient

server.port=8081

##############################################
# OPENAI CONFIGURATION
##############################################
#Docker container running Gemma3 on localhost:12434
spring.ai.openai.base-url=http://localhost:12434/v1
spring.ai.openai.api-key=dummy
spring.ai.openai.chat.model=ai/qwen3
spring.ai.openai.embedding.model=ai/nomic-embed-text-v1.5
spring.ai.openai.chat.enabled=true
spring.ai.openai.embedding.enabled=true


spring.ai.mcp.client.stdio.servers-configuration=classpath:mcp-servers-configuration.json

