spring.application.name=multimodelai

logging.level.com.openai=TRACE
logging.level.org.springframework.ai=TRACE
logging.level.okhttp3=DEBUG
logging.level.okhttp3.logging.HttpLoggingInterceptor=TRACE

#To disable the default Spring AI client and use custom clients for OpenAI and Ollama
spring.ai.chat.client.enabled=false

##############################################
# OPENAI CONFIGURATION
##############################################
#Docker container running Gemma3 on localhost:12434
spring.ai.openai.base-url=http://localhost:12434/v1
spring.ai.openai.api-key=dummy
spring.ai.openai.chat.model=ai/gemma3
spring.ai.openai.embedding.model=ai/nomic-embed-text-v1.5
spring.ai.openai.embedding.enabled=true

##############################################
# OLLAMA CONFIGURATION
##############################################
#Ollama configuration for deepseek-r1:7b model running on localhost:11434 (default Ollama port)
#Default for ollam embeddings is : mxbai-embed-large
spring.ai.ollama.chat.model=deepseek-r1:7b
spring.ai.ollama.embedding.enabled=false


##############################################
# ANTHROPIC CONFIGURATION
##############################################
spring.ai.anthropic.chat.model=claude-3
spring.ai.anthropic.api-key=${ANTHROPIC_API_KEY}


##############################################
# POSTGRESQL DATABASE
##############################################
spring.datasource.url=jdbc:postgresql://localhost:5432/chatmemory
spring.datasource.username=postgres
spring.datasource.password=Hanu@2025
spring.datasource.driver-class-name=org.postgresql.Driver

spring.ai.chat.memory.repository.jdbc.initialize-schema=always

##############################################
# DOCKER COMPOSE
##############################################
spring.docker.compose.file=Spring AI/multimodelai/docker-compose.yml
spring.docker.compose.stop.command=down

##############################################
# QDRANT VECTOR STORE CONFIGURATION
##############################################
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=documents
spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.enabled=true

###############################################
# REDIS CONFIGURATION
###############################################
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.ai.cache.redis.enabled=true

logging.level.org.springframework.ai.embedding=DEBUG
logging.level.org.springframework.ai.vectorstore=DEBUG

logging.level.org.springframework.ai.chat.cache=TRACE
logging.level.org.springframework.ai.vectorstore.redis.cache.semantic=TRACE
logging.level.org.springframework.ai.advisor=TRACE