spring.application.name=multimodelai

logging.level.com.openai=TRACE
logging.level.org.springframework.ai=TRACE
logging.level.okhttp3=DEBUG
logging.level.okhttp3.logging.HttpLoggingInterceptor=TRACE

#To disable the default Spring AI client and use custom clients for OpenAI and Ollama
spring.ai.chat.client.enabled=false

#Docker container running Gemma3 on localhost:12434
spring.ai.openai.base-url=http://localhost:12434/v1
spring.ai.openai.api-key=dummy
spring.ai.openai.chat.model=ai/gemma3

#Ollama configuration for deepseek-r1:7b model running on localhost:11434 (default Ollama port)
spring.ai.ollama.chat.model=deepseek-r1:7b

#Anthropic configuration for Claude 3 model
spring.ai.anthropic.chat.model=claude-3
spring.ai.anthropic.api-key=${ANTHROPIC_API_KEY}


# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/chatmemory
spring.datasource.username=postgres
spring.datasource.password=Hanu@2025
spring.datasource.driver-class-name=org.postgresql.Driver

spring.ai.chat.memory.repository.jdbc.initialize-schema=always
